version: 2
updates:
  - package-ecosystem: npm
    directory: /plus-ui
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - type:dependencies
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: maven
    directory: /source
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - type:dependencies
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    labels:
      - type:dependencies
      - dependencies
    commit-message:
      prefix: chore
      include: scope
