# Tomcat
server:
  port: 8106

# Spring
spring:
  application:
    name: ruoyi-appcenter
  profiles:
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
