server {
    listen 80;
    server_name _;
    client_max_body_size 200m;

    root /usr/share/nginx/html;
    index index.html;

    location /prod-api/ {
        proxy_pass http://ruoyi-gateway:8180/;
        proxy_set_header Host $host;
        proxy_set_header X-External-Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /admin {
        try_files /index.html =404;
    }

    location /admin/ {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.mjs$ {
        types {
            application/javascript mjs;
        }
        default_type application/javascript;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
